#############################################################################
# Makefile for building: bin/sparsedense
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue Dec 16 17:15:21 2014
# Project:  sparsedense.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile sparsedense.pro
#############################################################################

####### Compiler, tools and options

CC            = /opt/intel/impi/5.0.2.044/intel64/bin/mpicxx
CXX           = /opt/intel/impi/5.0.2.044/intel64/bin/mpicxx
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -Isrc
LINK          = /opt/intel/impi/5.0.2.044/intel64/bin/mpicxx
LFLAGS        = -dynamic -Wl,-O1
LIBS          = $(SUBLIBS)   -L${HOME}/Libraries/linuxAMD64 -lpardiso500-GNU472-X86-64 -L/opt/intel/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lmkl_blacs_intelmpi_lp64 -lmkl_blas95_lp64 -lmkl_scalapack_lp64 -fopenmp -lgfortran 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/CSRcomplex.cpp \
		src/CSRdouble.cpp \
		src/IO.cpp \
		src/Keywords.cpp \
		src/KeywordsBase.cpp \
		src/Options.cpp \
		src/ParDiSO.cpp \
		src/Parse.cpp \
		src/SelInvProcess.cpp \
		src/Solver.cpp \
		src/tools.cpp \
		src/main.cpp 
OBJECTS       = obj/CSRcomplex.o \
		obj/CSRdouble.o \
		obj/IO.o \
		obj/Keywords.o \
		obj/KeywordsBase.o \
		obj/Options.o \
		obj/ParDiSO.o \
		obj/Parse.o \
		obj/SelInvProcess.o \
		obj/Solver.o \
		obj/tools.o \
		obj/main.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sparsedense.pro
QMAKE_TARGET  = sparsedense
DESTDIR       = bin/
TARGET        = bin/sparsedense

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sparsedense.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile sparsedense.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile sparsedense.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/sparsedense1.0.0 || $(MKDIR) obj/sparsedense1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/sparsedense1.0.0/ && (cd `dirname obj/sparsedense1.0.0` && $(TAR) sparsedense1.0.0.tar sparsedense1.0.0 && $(COMPRESS) sparsedense1.0.0.tar) && $(MOVE) `dirname obj/sparsedense1.0.0`/sparsedense1.0.0.tar.gz . && $(DEL_FILE) -r obj/sparsedense1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/CSRcomplex.o: src/CSRcomplex.cpp src/CSRcomplex.hpp \
		src/config.hpp \
		src/searchingsorting.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CSRcomplex.o src/CSRcomplex.cpp

obj/CSRdouble.o: src/CSRdouble.cpp src/CSRdouble.hpp \
		src/config.hpp \
		src/searchingsorting.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CSRdouble.o src/CSRdouble.cpp

obj/IO.o: src/IO.cpp src/config.hpp \
		src/IO.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IO.o src/IO.cpp

obj/Keywords.o: src/Keywords.cpp src/config.hpp \
		src/Keywords.hpp \
		src/KeywordsBase.hpp \
		src/Parse.hpp \
		src/Matrix2D.hpp \
		src/Options.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Keywords.o src/Keywords.cpp

obj/KeywordsBase.o: src/KeywordsBase.cpp src/KeywordsBase.hpp \
		src/Parse.hpp \
		src/config.hpp \
		src/Matrix2D.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/KeywordsBase.o src/KeywordsBase.cpp

obj/Options.o: src/Options.cpp src/config.hpp \
		src/Options.hpp \
		src/Matrix2D.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Options.o src/Options.cpp

obj/ParDiSO.o: src/ParDiSO.cpp src/ParDiSO.hpp \
		src/config.hpp \
		src/CSRdouble.hpp \
		src/CSRcomplex.hpp \
		src/shared_var.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ParDiSO.o src/ParDiSO.cpp

obj/Parse.o: src/Parse.cpp src/Parse.hpp \
		src/config.hpp \
		src/Matrix2D.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Parse.o src/Parse.cpp

obj/SelInvProcess.o: src/SelInvProcess.cpp src/SelInvProcess.hpp \
		src/CSRdouble.hpp \
		src/config.hpp \
		src/Matrix2D.hpp \
		src/ParDiSO.hpp \
		src/Options.hpp \
		src/Solver.hpp \
		src/timing.hpp \
		src/shared_var.h \
		src/RealMath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/SelInvProcess.o src/SelInvProcess.cpp

obj/Solver.o: src/Solver.cpp src/Solver.hpp \
		src/CSRdouble.hpp \
		src/config.hpp \
		src/ParDiSO.hpp \
		src/timing.hpp \
		src/shared_var.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Solver.o src/Solver.cpp

obj/tools.o: src/tools.cpp src/CSRdouble.hpp \
		src/config.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tools.o src/tools.cpp

obj/main.o: src/main.cpp src/config.hpp \
		src/CSRdouble.hpp \
		src/IO.hpp \
		src/ParDiSO.hpp \
		src/Solver.hpp \
		src/timing.hpp \
		src/shared_var.h \
		src/SelInvProcess.hpp \
		src/Matrix2D.hpp \
		src/Options.hpp \
		src/RealMath.hpp \
		src/smat.h \
		src/Keywords.hpp \
		src/KeywordsBase.hpp \
		src/Parse.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

